version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    working_directory: ~/circleci-app
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-app

  test:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers

    working_directory: ~/circleci-app
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rspec --color --require spec_helper --format RspecJunitFormatter --out ~/rspec/rspec.xml spec --format progress
      - store_test_results:
          path: ~/rspec

workflows:
  version: 2
  main:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - bundle_dependencies